# Give the project a nice name
spring.application.name: frontend

# Set the port
server.port: ${SERVER_PORT:8080}

# Enable all the actuator endpoints for HTTP (keep them under the base path) and JMX
management.endpoints:
  web:
    base-path: /
    exposure.include: "*"
  jmx.exposure.include: "*"
