- hosts: frontend
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  post_tasks:
    - include_tasks: include_event.yml
      vars:
        application: deploy_frontend


  tasks:

    - include_tasks: include_deploy_boot.yml
      vars:
        application: frontend
