- hosts: frontend
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  post_tasks:
    - include_tasks: include_event.yml
      vars:
        application: restart_frontend


  tasks:

    - name: Stop the frontend application
      systemd: name="frontend" state=stopped

    - name: Wait while the application is down
      pause: seconds=30

    - name: Start the frontend application again
      systemd: name="frontend" state=started

    - name: Wait for the Java application to start up
      pause: seconds=30

    - name: Check if the service is available
      uri: url="https://{{ inventory_hostname }}/health"
      register: response
      ignore_errors: yes
