heartbeat.monitors:

- type: http
  urls: ["http://{{ frontend_server }}/health"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["http://{{ backend_server }}/health"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["{{ elasticsearch_host }}"]
  username: {{ elasticsearch_user }}
  password: {{ elasticsearch_password }}
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: tcp
  hosts: ["{{ mysql_server }}"]
  schedule: "@every 10s"
  timeout: 3s

- type: tcp
  hosts: ["{{ apm_server }}"]
  schedule: "@every 10s"
  timeout: 3s


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ elasticsearch_user }}"
    password: "${ES_PWD}"
  dashboards.enabled: true
