heartbeat.monitors:

- type: http
  urls: ["https://{{ domain }}/health"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["https://backend.{{ domain }}/health"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["https://kibana.{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["{{ elasticsearch_host }}"]
  username: {{ elasticsearch_user }}
  password: "${ES_PWD}"
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["{{ apm_server }}/healthcheck"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: tcp
  hosts: ["{{ mysql_server }}:3306"]
  schedule: "@every 10s"
  timeout: 3s
  name: mysql


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"


# No setup since Uptime Monitoring is part of Kibana
